os: linux
dist: xenial
language: python
python:
  - 2.7
  - 3.6
  - 3.8
env:
  - REQUESTS=2.24.0
install:
  - pip install -q requests==$REQUESTS
  - pip install -r requirements.txt
  - pip install -e .
script: python -m unittest discover tests/ '*test.py'
